/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    Articles: Article;
    media: Media;
    subsections: Subsection;
    sections: Section;
    bestSelections: BestSelection;
    continueSelections: ContinueSelection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    Articles: ArticlesSelect<false> | ArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subsections: SubsectionsSelect<false> | SubsectionsSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    bestSelections: BestSelectionsSelect<false> | BestSelectionsSelect<true>;
    continueSelections: ContinueSelectionsSelect<false> | ContinueSelectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    collectionsPage: CollectionsPage;
    homePage: HomePage;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    collectionsPage: CollectionsPageSelect<false> | CollectionsPageSelect<true>;
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Статьи для сайта — управляйте контентом здесь
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Articles".
 */
export interface Article {
  id: number;
  status: 'draft' | 'published';
  title: string;
  slug: string;
  /**
   * Выберите подборку. Раздел и категория подтянутся автоматически.
   */
  subsection: number | Subsection;
  /**
   * Заполняется автоматически из выбранной подборки.
   */
  section?: string | null;
  /**
   * Берётся из поля category в subsections.
   */
  category?: string | null;
  /**
   * Генерируется автоматически из section, subsection и slug.
   */
  href?: string | null;
  /**
   * Краткий анонс статьи для карточек и превью.
   */
  description: string;
  /**
   * Первый текстовый блок статьи, который задаёт контекст.
   */
  intro: string;
  /**
   * Главное изображение статьи для карточек, превью и SEO.
   */
  image: number | Media;
  /**
   * Например: 5 , 8, 12 .
   */
  readTime: string;
  /**
   * Имя автора статьи.
   */
  author: string;
  /**
   * Короткие факты и ключевые данные по статье.
   */
  kratko_items?:
    | {
        /**
         * Выберите подходящую иконку для пункта.
         */
        icon: 'DollarSign' | 'FileText' | 'MapPin' | 'ShieldAlert' | 'Clock' | 'User';
        /**
         * Название пункта.
         */
        label: string;
        /**
         * Значение пункта.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Основные смысловые блоки статьи.
   */
  content_blocks?:
    | {
        /**
         * Заголовок блока.
         */
        title: string;
        /**
         * Текст блока. Доступно форматирование: жирный, ссылки, списки. Переносы строк и пробелы сохраняются.
         */
        description: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Тип дополнительного контента внутри блока.
         */
        contentType?: ('none' | 'table' | 'warning' | 'checklist' | 'tips') | null;
        /**
         * Настройте заголовки и строки таблицы.
         */
        table?: {
          headers: {
            header1: string;
            header2: string;
            header3: string;
          };
          rows?:
            | {
                cell1: string;
                cell2: string;
                cell3: string;
                id?: string | null;
              }[]
            | null;
        };
        /**
         * Текст важного предупреждения.
         */
        warning?: string | null;
        /**
         * Добавьте пункты чек-листа.
         */
        checklist?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Текст полезного совета.
         */
        tips?: string | null;
        /**
         * Текст после таблицы/чек-листа/совета. Доступно форматирование: жирный, ссылки, списки.
         */
        descriptionAfter?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Добавьте ссылки на статьи, разделы или подборки. Ссылка берётся автоматически из выбранного элемента.
   */
  useful_links?:
    | {
        /**
         * Текст который будет отображаться
         */
        label: string;
        /**
         * Выберите тип элемента для ссылки
         */
        linkType: 'article' | 'section' | 'subsection';
        /**
         * Выберите статью — ссылка возьмётся автоматически
         */
        article?: (number | null) | Article;
        /**
         * Выберите раздел — ссылка возьмётся автоматически
         */
        section?: (number | null) | Section;
        /**
         * Выберите подборку — ссылка возьмётся автоматически
         */
        subsection?: (number | null) | Subsection;
        id?: string | null;
      }[]
    | null;
  /**
   * Выберите статьи, которые нужно показать в блоке похожих. Текущая статья исключена из выбора.
   */
  related_articles?: (number | Article)[] | null;
  /**
   * Параметры для поиска и отображения в выдаче.
   */
  seo: {
    /**
     * Заголовок для поисковиков и соцсетей.
     */
    title: string;
    /**
     * Краткое описание страницы для поиска.
     */
    description: string;
    /**
     * Ключевые слова через отдельные элементы списка.
     */
    keywords: {
      keyword: string;
      id?: string | null;
    }[];
    /**
     * Включи, если страницу не нужно индексировать.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsections".
 */
export interface Subsection {
  id: number;
  status: 'draft' | 'published';
  title: string;
  slug: string;
  /**
   * Выберите раздел вручную.
   */
  section: number | Section;
  /**
   * Введите категорию вручную.
   */
  category: string;
  href?: string | null;
  description: string;
  intro: string;
  image: number | Media;
  /**
   * Выберите подборку — bestArticles заполнится автоматически
   */
  bestSelection?: (number | null) | BestSelection;
  /**
   * Выберите подборку — continuePlanning заполнится автоматически
   */
  continueSelection?: (number | null) | ContinueSelection;
  search?: {
    placeholder?: string | null;
    tags?:
      | {
          title: string;
          icon: 'utensilsCrossed' | 'map' | 'waves' | 'bus' | 'dollarSign' | 'fileText' | 'lifeBuoy';
          id?: string | null;
        }[]
      | null;
  };
  seo: {
    title: string;
    description: string;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  status: 'draft' | 'published';
  title: string;
  /**
   * Например: on-island, before-trip. Только латиница и дефисы.
   */
  slug: string;
  /**
   * Генерируется автоматически из slug
   */
  href?: string | null;
  description?: string | null;
  search?: {
    placeholder?: string | null;
    tags?:
      | {
          title: string;
          icon: 'utensilsCrossed' | 'map' | 'waves' | 'bus' | 'dollarSign' | 'fileText' | 'lifeBuoy';
          id?: string | null;
        }[]
      | null;
  };
  image: number | Media;
  /**
   * Выберите подборку — лучшие статьи отобразятся на странице раздела
   */
  bestSelection?: (number | null) | BestSelection;
  /**
   * Выберите подборку — статьи отобразятся в блоке "Продолжить чтение"
   */
  continueSelection?: (number | null) | ContinueSelection;
  seo: {
    title: string;
    description: string;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bestSelections".
 */
export interface BestSelection {
  id: number;
  status: 'draft' | 'published';
  title: string;
  /**
   * В БД хранятся только ID. Данные формируются автоматически.
   */
  bestArticles: (number | Article)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "continueSelections".
 */
export interface ContinueSelection {
  id: number;
  status: 'draft' | 'published';
  title: string;
  /**
   * В БД хранятся только ID. Данные формируются автоматически.
   */
  continuePlanning: (number | Article)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'Articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subsections';
        value: number | Subsection;
      } | null)
    | ({
        relationTo: 'sections';
        value: number | Section;
      } | null)
    | ({
        relationTo: 'bestSelections';
        value: number | BestSelection;
      } | null)
    | ({
        relationTo: 'continueSelections';
        value: number | ContinueSelection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  slug?: T;
  subsection?: T;
  section?: T;
  category?: T;
  href?: T;
  description?: T;
  intro?: T;
  image?: T;
  readTime?: T;
  author?: T;
  kratko_items?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  content_blocks?:
    | T
    | {
        title?: T;
        description?: T;
        contentType?: T;
        table?:
          | T
          | {
              headers?:
                | T
                | {
                    header1?: T;
                    header2?: T;
                    header3?: T;
                  };
              rows?:
                | T
                | {
                    cell1?: T;
                    cell2?: T;
                    cell3?: T;
                    id?: T;
                  };
            };
        warning?: T;
        checklist?:
          | T
          | {
              item?: T;
              id?: T;
            };
        tips?: T;
        descriptionAfter?: T;
        id?: T;
      };
  useful_links?:
    | T
    | {
        label?: T;
        linkType?: T;
        article?: T;
        section?: T;
        subsection?: T;
        id?: T;
      };
  related_articles?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsections_select".
 */
export interface SubsectionsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  slug?: T;
  section?: T;
  category?: T;
  href?: T;
  description?: T;
  intro?: T;
  image?: T;
  bestSelection?: T;
  continueSelection?: T;
  search?:
    | T
    | {
        placeholder?: T;
        tags?:
          | T
          | {
              title?: T;
              icon?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  slug?: T;
  href?: T;
  description?: T;
  search?:
    | T
    | {
        placeholder?: T;
        tags?:
          | T
          | {
              title?: T;
              icon?: T;
              id?: T;
            };
      };
  image?: T;
  bestSelection?: T;
  continueSelection?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bestSelections_select".
 */
export interface BestSelectionsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  bestArticles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "continueSelections_select".
 */
export interface ContinueSelectionsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  continuePlanning?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collectionsPage".
 */
export interface CollectionsPage {
  id: number;
  status: 'draft' | 'published';
  title: string;
  description?: string | null;
  image: number | Media;
  search?: {
    placeholder?: string | null;
    tags?:
      | {
          title: string;
          icon: 'utensilsCrossed' | 'map' | 'waves' | 'bus' | 'dollarSign' | 'fileText' | 'lifeBuoy';
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Опционально — лучшие статьи отобразятся вверху страницы.
   */
  bestSelection?: (number | null) | BestSelection;
  /**
   * Опционально — статьи отобразятся в блоке «Продолжить чтение».
   */
  continueSelection?: (number | null) | ContinueSelection;
  seo: {
    title: string;
    description: string;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  status: 'draft' | 'published';
  heroSection: {
    title: string;
    description: string;
    image: number | Media;
    search?: {
      placeholder?: string | null;
      tags?:
        | {
            title: string;
            icon: 'utensilsCrossed' | 'map' | 'waves' | 'bus' | 'dollarSign' | 'fileText' | 'lifeBuoy';
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Выберите 3 статьи для блока "Популярные". Извлекутся: title, description, image, category, readTime.
   */
  popularArticles?: (number | Article)[] | null;
  planningBlock?: {
    /**
     * Выберите 4 статьи для блока "Планирование".
     */
    articles?: (number | Article)[] | null;
    /**
     * Добавьте иконки для каждой статьи (в том же порядке).
     */
    icons?:
      | {
          icon: 'Sun' | 'BookType' | 'Wallet' | 'House' | 'Plane' | 'Map' | 'Waves' | 'Utensils';
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Выберите подборки для блока "Подборки". Извлекутся: title, description, image, category.
   */
  collections?: (number | Subsection)[] | null;
  urgentBlock?: {
    /**
     * Выберите 4 статьи для блока "Срочное".
     */
    articles?: (number | Article)[] | null;
    /**
     * Добавьте иконки для каждой статьи (в том же порядке).
     */
    icons?:
      | {
          icon: 'Sun' | 'BookType' | 'Wallet' | 'House' | 'Plane' | 'Map' | 'Waves' | 'Utensils';
          id?: string | null;
        }[]
      | null;
  };
  seo: {
    title: string;
    description: string;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  status: 'draft' | 'published';
  /**
   * Добавьте до 8 пунктов навигации. Ссылка берётся автоматически из выбранного элемента.
   */
  navigationItems?:
    | {
        /**
         * Текст который будет отображаться в меню
         */
        title: string;
        /**
         * Выберите иконку для пункта меню
         */
        icon:
          | 'Map'
          | 'Plane'
          | 'Hotel'
          | 'UtensilsCrossed'
          | 'MapPin'
          | 'Car'
          | 'DollarSign'
          | 'Lightbulb'
          | 'LifeBuoy'
          | 'List'
          | 'Star'
          | 'Calendar'
          | 'Waves'
          | 'Palmtree'
          | 'Camera'
          | 'Backpack';
        /**
         * Выберите тип элемента для ссылки
         */
        linkType: 'section' | 'subsection' | 'article' | 'external';
        /**
         * Выберите раздел — ссылка возьмётся автоматически
         */
        section?: (number | null) | Section;
        /**
         * Выберите подборку — ссылка возьмётся автоматически
         */
        subsection?: (number | null) | Subsection;
        /**
         * Выберите статью — ссылка возьмётся автоматически
         */
        article?: (number | null) | Article;
        /**
         * Например: https://t.me/phuquocclub
         */
        externalUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  status: 'draft' | 'published';
  /**
   * Текст описания в левом блоке футера
   */
  description?: string | null;
  socialLinks?: {
    telegram?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  sectionPlanning?: {
    title?: string | null;
    item1?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item2?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item3?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item4?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item5?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
  };
  sectionOnIsland?: {
    title?: string | null;
    item1?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item2?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item3?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item4?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item5?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item6?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
  };
  sectionPractice?: {
    title?: string | null;
    item1?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item2?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item3?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item4?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item5?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
  };
  sectionRoutes?: {
    title?: string | null;
    item1?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item2?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item3?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item4?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    item5?: {
      label?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
  };
  additionalLinks?: {
    link1?: {
      title?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    link2?: {
      title?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    link3?: {
      title?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
    link4?: {
      title?: string | null;
      linkType?: ('section' | 'subsection' | 'article' | 'external') | null;
      section?: (number | null) | Section;
      subsection?: (number | null) | Subsection;
      article?: (number | null) | Article;
      externalUrl?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collectionsPage_select".
 */
export interface CollectionsPageSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  description?: T;
  image?: T;
  search?:
    | T
    | {
        placeholder?: T;
        tags?:
          | T
          | {
              title?: T;
              icon?: T;
              id?: T;
            };
      };
  bestSelection?: T;
  continueSelection?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  status?: T;
  heroSection?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        search?:
          | T
          | {
              placeholder?: T;
              tags?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    id?: T;
                  };
            };
      };
  popularArticles?: T;
  planningBlock?:
    | T
    | {
        articles?: T;
        icons?:
          | T
          | {
              icon?: T;
              id?: T;
            };
      };
  collections?: T;
  urgentBlock?:
    | T
    | {
        articles?: T;
        icons?:
          | T
          | {
              icon?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  status?: T;
  navigationItems?:
    | T
    | {
        title?: T;
        icon?: T;
        linkType?: T;
        section?: T;
        subsection?: T;
        article?: T;
        externalUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  status?: T;
  description?: T;
  socialLinks?:
    | T
    | {
        telegram?: T;
        instagram?: T;
        youtube?: T;
      };
  sectionPlanning?:
    | T
    | {
        title?: T;
        item1?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item2?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item3?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item4?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item5?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
      };
  sectionOnIsland?:
    | T
    | {
        title?: T;
        item1?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item2?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item3?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item4?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item5?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item6?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
      };
  sectionPractice?:
    | T
    | {
        title?: T;
        item1?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item2?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item3?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item4?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item5?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
      };
  sectionRoutes?:
    | T
    | {
        title?: T;
        item1?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item2?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item3?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item4?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        item5?:
          | T
          | {
              label?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
      };
  additionalLinks?:
    | T
    | {
        link1?:
          | T
          | {
              title?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        link2?:
          | T
          | {
              title?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        link3?:
          | T
          | {
              title?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
        link4?:
          | T
          | {
              title?: T;
              linkType?: T;
              section?: T;
              subsection?: T;
              article?: T;
              externalUrl?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}